sudo: required

services:
  - docker

language: java
dist: trusty
jdk: oraclejdk8

env:
  matrix:
    - COVERAGE=0.5 TARGET=/monolithic/ui
    - COVERAGE=0.5 TARGET=/monolithic/service/cart
    - COVERAGE=0.5 TARGET=/monolithic/service/user
    - COVERAGE=0.3 TARGET=/monolithic/repository/order
    - COVERAGE=0.5 TARGET=/monolithic/repository/cart
    - COVERAGE=0.5 TARGET=/monolithic/repository/product
    - COVERAGE=0.3 TARGET=/monolithic/repository/user
  global:
    - secure: U/xsqFpiCNFK/qGcN36ut4ybr+I5d4EKQ3Sl+U8S67jrtOK5ai+QQEZCsiwYlty/Q8smQ11lDSwruGJN+JZxouvsNO8gEuZhQ5/L205/TXVseP8cUzDtciWQxLxby/bvSpOsFQM9LtfZCiWSzWhQK03CPVaT7HXyGByhd45bKdEiVQHbKW4HmTZz52XKQB5qYmIBIA94lWoQjXUcm8Ju2iA5YmwitDuKI4aTxha25i/Mj8LbNA4FoWy96k2ihYhCU6unQZPmv56ButPrOERq9GYoo5lshldrpVnvVCfFT9n9kXnZKz7GIqwmzzpmvt24B4r21sk57nTG1Wdysmxy8HRKChGiPQTREyihwKODMe7HicsQwHlqVLEV0jTNe+lzVqEYjYb+bk1htRALeXHDrAp/v0Cx1s3VyY/O/I18nyG+HK70O4voCFyjc2ZqITWNpDDhtvje3tfSnC3SMXUhks+GKUpWfFJrVIz7himcNkKKBKN3f/CYq81yyGZ8Aj6wkCJfhq9SzE1tukExLH0imZoS19LPfOX/swjFANb6k//SlJMVkakyK5o0leJUJWTHkpiDMAxz7lYARyJydG8caVJobxrAbRVmam4Z0a9oQM/1qv5Jrz01PdDyv81EfdUG8GdZ1ASiowOKSMOwYcvHVw8dMYbaxyHgVpALQLu3Sa8=
    - secure: T94Mnol7pSiSkONg5tZekDmApGkN/ZnEAeF6AOXYRBAPtJ+4SOzO035ZroGr7jIlqPfuFdb4aEU1Z894u1Rrqlt/jlV0H8Uu9Pqjm6fZM1KOoKezLPcXQ3kgG9ka2QArQigBVoDIUuZwZsNG+lmYNlYUzJ9rvIbMy0JYikySdkzfRxRJR5gWWGj4k53aaPlbjNSDwnDnnKncq3yz1Wuhydy0Ptilv2m8jyUieAEGNkaFRYZHZS6gBjK1DWhJ7W7wiqYVogmi95es4li8250lStBMJ5IUYIXyXu0tQgKlIy0Y4NgjRtylgNjsVuy+nMg9o8mmvpyPZclNJLCeoaUsSt9DnEwcZGAkhfzYQPbDJ83jYS++NvgXx0WvPAFOTTNWefyl2RpXMcBHxTFxTNwUiBci6sKlFgJlid10uOwz21t4A6mDzF5gNOq6DRoyOuPetgxkSYAuP9WBsI21nvfw9w+PN9nqTIIAQ+nMizQE49w9CieDM40QWLo1mvXmQ8eKLbGXfS2Zq+kE3qqodEt8eCkp2twKOSBJISwaWp7i6ssBU5vHnyhCFahqRsc0PIkDVnREf/GNI24iShGbwkh/yQoWA0+a+hdbJHL2mz0O86sn4SYQdG/azO4noJLAyj1PKRNMkvllZVIRRxbdoo8KS1NmVlN/H/BM1w7RVRIcSxU=

install:
  - "./gradlew clean jar"

script:
  - COVERAGE=${COVERAGE} ./gradlew -p .${TARGET} check

after_success:
  - find . -name jacocoTestReport.csv | xargs cat | awk -F',' '{print $3" "$4" "$5}'

deploy:
  provider: script
  script: bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username \"${DOCKER_LOGIN}\" --password-stdin"
  on:
    all_branches: true
