language: java
dist: trusty
jdk: oraclejdk8

env:
  - COVERAGE=0.5 TARGET=/monolithc/ui
  - COVERAGE=0.5 TARGET=/monolithc/service/cart
  - COVERAGE=0.5 TARGET=/monolithc/service/user
  - COVERAGE=0.5 TARGET=/monolithc/repository/order
  - COVERAGE=0.5 TARGET=/monolithc/repository/cart
  - COVERAGE=0.5 TARGET=/monolithc/repository/product
  - COVERAGE=0.5 TARGET=/monolithc/repository/user

install:
  - ./gradlew clean jar

script:
  - COVERAGE=${COVERAGE} ./gradlew -p ${TARGET} check

after_success:
  - find . -name jacocoTestReport.csv | xargs cat | awk -F',' '{print $3" "$4" "$5}'

deploy:
  provider: script
  script: echo "WIP"
  on:
    all_branches: true
