language: java
dist: trusty
jdk: oraclejdk8

install:
  - ./gradlew clean jar

script:
#  - echo "Testing coming soon"
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv | xargs cat | awk -F',' '{print $3" "$4" "$5}'
